version: '3'
services:    
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      ES_JAVA_OPTS: '-Xms256m -Xmx256m'
      discovery.type: single-node
    container_name : esearch
    volumes:
      - esdata:/usr/share/elasticsearch/data
  rabbitmq:
    hostname: 'my_rabbit'
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rmqdata:/var/lib/rabbitmq
    container_name: rabbitmq
    
volumes:
  esdata:
    driver: local
  rmqdata:
    driver: local